[features]
seeds = false
[programs.devnet]
myepicproject = "GGfbywqoheBvuVRM45iNCEtuWJNqF1RqAfokfMsrRtNA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/miha/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
